name: Continuous Integration

on:
  push:
  pull_request:
    types:
      - reopened

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test the application
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install PSQL
        run: |
          apt update
          apt install -y postgresql-client
      - name: Install Diesel CLI
        run: cargo install diesel_cli --no-default-features --features postgres
      - name: Build the application
        run: cargo build --verbose
      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/url-shortener
        run: |
          bash ./scripts/run-tests.sh --touch-env

  lint:
    runs-on: ubuntu-latest
    name: Lint the application
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Clippy
        run: rustup component add clippy
      - name: Run linter
        run: cargo clippy --verbose --all-targets --all-features -- -D warnings
